package bilutleieapp.enums;

public enum Color {
    SVART, HVIT, SØLV, RØD, BLÅ, GRÅ, GRØNN, GUL, ORANSJE, LILLA,
    BRUN, ROSA, BEIGE, TURKIS, LYSEBLÅ, FIOLET, CYAN, MAGENTA, KREM, OLIVEN,
    INDIGO, KARMIN, KHAKI, FALURØD, ENGELSK_RØDT, CERULEAN, SINOBER, SKARLAGEN, ULTRAMARIN, VERDIGRIS
}

